### ISSUE TITLE
[request] Replace featured badge on user popout with information

### ISSUE THREAD

**Issue by pointydev** [DoctorMcKay/steam-profile-detailed-status#2]
Heya,

So I was looking for a plugin to assist me in my efforts in accepting people to a "years of service groups" chain that would let me check peoples' creation dates effectively, and this script does exactly that with no buff. However I have an idea that would make my job even easier, and would just be a general QOL improvement.

I suggest replacing (or adding next to) the featured badge in the user profile popout (shown below) on mouseover, allowing for quick access to the information currently available with this script already. Since we're already querying `GetPlayerSummaries` there would be no extra endpoints to deal with, just an extra request when each popout loads along with a different place to put the information.

![](https://pointy.needs-to-s.top/2VcARy7.png)

Thanks,
Elliott

**Comment by DoctorMcKay** [comment]
![](https://user-images.githubusercontent.com/1538723/64328279-2ccca380-cf9b-11e9-8c39-d4a3a6525892.png)

Done.
